spring.application.name=finance-batch
server.port=8080


# Conexión a PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/finance_db
spring.datasource.username=postgres
spring.datasource.password=fec4a5n5

# Configuración de JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Inicializar tablas de Spring Batch
spring.batch.jdbc.initialize-schema=always

# --- CONTROL DE EJECUCIÓN ---
# Descomenta la línea del trabajo que quieras ejecutar.
# Si comentas ambas, o borras esta línea, Spring intentará ejecutar TODOS.

# Deshabilitar ejecución automática de jobs al inicio
spring.batch.job.enabled=false

#spring.batch.job.name=reporteDiarioJob
#spring.batch.job.name=calculoInteresesJob
#spring.batch.job.name=estadosAnualesJob
eureka.client.serviceUrl.defaultZone=${EUREKA_URL:http://localhost:8761/eureka/}
eureka.instance.prefer-ip-address=true

spring.kafka.bootstrap-servers=finance-kafka:9092
